name: Build and Deploy Flask App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up virtual environment
      run: |
        cd note_app
        python3 -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip setuptools wheel build

    - name: Build 
      run: |
        cd note_app
        source .venv/bin/activate
        python3 -m build

    - name: Install 
      run: |
        cd note_app
        cp dist/napp*.whl /home/hubertas/hosted_app/
        cd /home/hubertas/hosted_app/
        python3 -m venv .venv
        source .venv/bin/activate
        ls
        pip install *.whl --force-reinstall

    - name: Restart app using systemd
      run: |
        sudo systemctl restart note_app.service
