name: Build and Deploy Flask App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up virtual environment
      run: |
        cd note_app
        python3 -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip setuptools wheel

    - name: Build and install app
      run: |
        source .venv/bin/activate
        pip install .

    - name: Restart app using systemd
      run: |
        sudo systemctl restart note_app.service
